### ISSUE TITLE
pygame.error: posted event keycode must be int

### ISSUE THREAD

**Issue by zhaoyingnan179346** [qlan3/Explorer#4]
Thanks for your code.
1.When I run 'python main.py --config_file ./configs/catcher.json --config_idx 1', I got the error 'pygame.error: posted event keycode must be int' in 
  File "/home/zhaoyingnan/PycharmProjects/end-to-end-option/Explorer-my_own/agents/VanillaDQN.py", line 131, in run_episode
    self.next_state[mode], self.reward[mode], self.done[mode], _ = self.env[mode].step(self.action[mode])
I print the action is 0. 

2.When I run 'python main.py --config_file ./configs/minatar.json  --config_idx 1'
I got an error 
'  File "/home/zhaoyingnan/PycharmProjects/end-to-end-option/Explorer-my_own/agents/VanillaDQN.py", line 81, in createNN
    feature_net = Conv2d_MinAtar(in_channels=self.env[mode].game.state_shape()[2], feature_dim=layer_dims[0])
NameError: name 'mode' is not defined'
 Hoping for your reply about these two errors.

**Comment by qlan3** [comment]
Thank you for pointing out these bugs!
I fixed the second bug. However, I didn't see any bugs when I run` python main.py --config_file ./configs/catcher.json --config_idx 1`. What's your pygame version? I'm using 1.9.6.
I also updated the requirement file. Please check!

**Comment by zhaoyingnan179346** [comment]
Thanks！ My pygame version is 2.0.0, I change it to 1.9.6, it works!
I am interested in your results of figure 2. Could you please send me the code for it in the paper? It is the three algorithms using the simple MDP. I think simple MDP is convenient to verify some ideas.

**Comment by qlan3** [comment]
Great!
The MDP is modified from Rich Sutton's RL book. The code is here: https://github.com/ShangtongZhang/reinforcement-learning-an-introduction/blob/master/chapter06/maximization_bias.py
