### ISSUE TITLE
Bed performance

### ISSUE THREAD

**Issue by Tantao122200** [qlan3/Explorer#9]
Hi, I run minatar_Asterix as your minatat.json, the parameter is lr=1e-4, alpha=0.95, centered=true, eps=0.01, the numebr of MaxminDQN is 2, 4,6. But, I found that the performance of DQN, DDQN, Average DQN are the same as your papaer, but the proformance of Maxmin DQN is not right. Could you prive the best parameter of minatar environments?

**Comment by qlan3** [comment]
Hi,
Unfortunately, I've lost the experimental logs for all MinAtar results. However, I remember that the best lr for Maxmin DQN is usually larger than the best lr for DQN. Moreover, according to Figure 4(i) in my [paper](https://arxiv.org/pdf/2002.06487.pdf), the best N=4 for Asterix. So I suggest fixing N to 4 and pick the best lr from [3e-3, 1e-3, 3e-4, 1e-4, 3e-5]. If you still can't reproduce the result after this, please let me know.
